<iframe src="https://gamma.app/embed/x69ax0ijqo4j9ow" style="width: 700px; max-width: 100%; height: 450px" allow="fullscreen" title="IBM Cloud Platform: Driving Innovation and Improving User Experiences"></iframe>
